Remove replaces-only approach in FBC
operator-framework/operator-registry pull request #1065
Opened 2023-02-20 16:31 UTC by theishshah

This PR contains the initial logic and docs for cleaning up the FBC Z-stream replacements. Follow up work for this PR will include a unit testing deep dive spike and some re-factoring to pre-sort and filter versions.

streamlining & add'l namechanges to working utest, debug printfs removed
working idempotent approach across set of all channel entries; but gaps in utest and UGLY implementation refactor minimally-nested ifs
updated supporting docs
standardize on yaml.UnmarshallStrict to give better diagnostics for unexpected fields

2023-02-20 16:37 UTC, grokspawn commented on alpha/declcfg/write.go
> +	CrossChannelLinking  bool
I forgot that I left the cross-channel linking support in here.  It's not getting used by anything, but it ... also doesn't work. 
I'm open to leaving it as-is or breaking it out.

2023-02-20 16:43 UTC, grokspawn commented
Would you please retitle to something like `OPECO-2596: semver should generate replaces across Y-streams in minor-channel mode` and add solves #1031  ?

2023-03-01 16:04 UTC, everettraven requested changes
Overall looks pretty good, great work @theishshah!

The reason for me marking this review as requesting changes is some minor things I found in how the tests are written that I *think* could be contributing to the test failures.

Aside from that I had a few smaller nits.

2023-03-03 14:43 UTC, grokspawn commented on alpha/veneer/composite/builder.go
> +	err := yaml.UnmarshalStrict(vd.Config, basicConfig)
This comes back to a comment I put in the composite template origination PR where I was asking for strict field unmarshalling as well as validation of a minimum set of fields (https://github.com/operator-framework/operator-registry/pull/1054#discussion_r1074039456). 

Well, I got distracted and didn't follow up on it, and this part of it didn't happen.   This is a functionally equivalent approach which has the added benefit of disallowing unknown/unexpected members (https://pkg.go.dev/gopkg.in/yaml.v2#UnmarshalStrict). 

This is totally outside the original purview of this effort, and really just a "I found a clever way to cover this base".

2023-03-03 15:10 UTC, grokspawn commented on alpha/declcfg/write.go
> +	CrossChannelLinking  bool
Removing these entirely.  I had hoped that we'd be able to use this to visually debug the fact that we now can have `skips` in a channel which are not part of the channel (but within the Y range of the channel). 
But alas, it was just a bit too much effort for the time available.

2023-03-03 15:17 UTC, grokspawn commented on alpha/veneer/semver/types.go
> +type entryList []entryTuple
Nah, we can totally do without it.  In one of the interim attempts for this feature, the entryList was a complex structure, so abstracting it made sense.  This was just left in as an available 'rough edge' to sand off.

2023-03-03 16:13 UTC, merged