[BUGFIX] Allow absolute filepaths for resolving catalog config
operator-framework/operator-registry pull request #1128
Opened 2023-07-25 17:34 UTC by theishshah

**Description of the change:**
Adds an additional check to the Catalog Config fetching function to allow absolute file paths to be resolved. 

**Motivation for the change:**
When adding support for remote catalog configurations, the resolver lost the ability to use absolute filepaths and could only handle relative paths.

2023-07-25 17:51 UTC, everettraven reviewed
The changes look good to me. Do we need to make any test updates to verify that this change does indeed function as expected?

2023-07-31 12:59 UTC, grokspawn commented
I'd like to see a utest for this case since this (fetch or use local reference) is central to this template's usefulness.

2023-07-31 13:08 UTC, everettraven commented
>I'd like to see a utest for this case since this (fetch or use local reference) is central to this template's usefulness.

FWIW I think this is a test case that should be updated to force the `fakeGetter` to error and ensure we never see any errors (i.e we are using `os.Open` instead of the HTTP `.Get()`):

https://github.com/operator-framework/operator-registry/blob/68e13df96590977370ffcd1a8e9ff76e0f2a03f2/alpha/template/composite/composite_test.go#L567-L579

2023-08-01 19:36 UTC, everettraven commented on alpha/template/composite/composite_test.go
> +		},
I'm actually not sure this whole test case is necessary. Looking at lines 612 - 621 it looks like if we end up creating the file we actually set the file path provided to the `FetchCatalogConfig` function to be the absolute path. This makes me think that we should add `shouldError: true` under https://github.com/operator-framework/operator-registry/pull/1128/files#diff-0299f965ef1d5dc96c54539eccbbcbf7a35e5f38255886bcbb6f8c39edf3364fR574 and that would meet this criteria.

I think the "Failed file fetch" actually tests the relative path case by ensuring it attempts to get a relative path that doesn't exist and errors out.

2023-08-03 17:05 UTC, everettraven approved these changes

2023-08-03 17:09 UTC, dinhxuanvu requested changes

2023-08-03 17:09 UTC, dinhxuanvu commented on alpha/template/composite/composite.go
> +		// Evalute remote catalog config
Are those comments for the `else` case? If so, please correct the indentation or move the comments inside the else bracket is also fine.

2023-08-03 17:35 UTC, dinhxuanvu approved these changes
/approve
The bot will take care of the commit squashing after merge.

2023-08-03 17:50 UTC, merged