Add ConsoleYamlSamples to the supported resources
operator-framework/operator-registry pull request #432
Opened 2020-09-03 10:36 UTC by Jamstah

**Description of the change:**
Allow the inclusion of samples in the bundle manifest

https://github.com/operator-framework/operator-lifecycle-manager/issues/1615

**Motivation for the change:**
Ease of deployment of samples for the console

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

2020-09-03 10:40 UTC, Jamstah commented
/assign @ecordell

2020-09-03 20:39 UTC, exdx commented
/ok-to-test

2020-09-17 15:23 UTC, njhale requested changes

2020-09-17 15:23 UTC, njhale commented on pkg/lib/bundle/supported_resources.go
> +	ConsoleYamlSampleKind     = "ConsoleYamlSample"
I think these need to be added to OLM before we allow them to be added to bundles: https://github.com/operator-framework/operator-lifecycle-manager/blob/78bb41b4613cafca7264a3108d1f1fa4b66024c8/pkg/controller/operators/catalog/operator.go#L2080

2020-09-17 15:27 UTC, njhale commented on pkg/lib/bundle/supported_resources.go
> +	ConsoleYamlSampleKind     = "ConsoleYamlSample"
Ah, I see there's a PR open for it: https://github.com/operator-framework/operator-lifecycle-manager/pull/1616

2020-09-17 15:28 UTC, njhale commented
/hold

awaiting https://github.com/operator-framework/operator-lifecycle-manager/pull/1616

2020-11-02 14:02 UTC, exdx commented
/lgtm

2020-11-02 14:38 UTC, kevinrizza commented
/approve
/retest

2020-11-16 16:44 UTC, exdx commented
/hold cancel

2020-11-16 21:20 UTC, exdx commented
e2e aws currently having CI issues. this feels safe to override as its a trivial change. 
/override ci/prow/e2e-aws

2020-11-16 21:23 UTC, merged