feat: add opm support for optional validators and custom category validation
operator-framework/operator-registry pull request #495
Opened 2020-10-27 22:27 UTC by exdx

**Description of the change:**
Bumps the `api` dependency to incorporate the latest optional validators: the bundle object validator and the new operatorhub validator that enables usage of a custom categories file. 

Documented at https://olm.operatorframework.io/docs/tasks/validate-package/#validation

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

2020-10-29 15:12 UTC, kevinrizza requested changes

2020-10-29 15:12 UTC, kevinrizza commented on cmd/opm/alpha/bundle/validate.go
> +	bundleValidateCmd.Flags().StringVarP(&optional, "optional-validators", "o", "", "Specifies optional validations (operatorhub validation, bundle-objects validation, etc) to be run. For example, set t
Can we add an enumeration to the docs text for the set of valid values here?

2020-10-29 20:02 UTC, exdx commented
This is looking pretty much ready, but requires that the api view of the bundle and the registry view of the bundle be the same (so the registry can pass the api bundle down to the operatorhub validator). Will refactor in a separate PR so that there is only one consistent bundle definition living in api. 

/hold

2020-11-11 16:02 UTC, exdx commented
Decided to simply go with the manifest bundle type for the operatorhub validator (its a very straightforward validation - just looks at the versioned CSV object) and hold off on the refactor for now. The validators work as intended now.

```
operator-registry(feat/custom-validation-categories) ✗: OPERATOR_BUNDLE_CATEGORIES=../api/pkg/validation/internal/testdata/categories.json ./bin/opm alpha bundle validate --tag quay.io/dsover/bundle-categories:latest --image-builder docker -o operatorhub,bundle-object
INFO[0000] Create a temp directory at /var/folders/9z/c4spd5wn0q51kw278nmpsjpm0000gn/T/bundle-913462645  container-tool=docker
DEBU[0000] Pulling and unpacking container image         container-tool=docker
INFO[0000] running /usr/local/bin/docker pull quay.io/dsover/bundle-categories:latest  container-tool=docker
INFO[0001] running docker create                         container-tool=docker
DEBU[0001] [docker create quay.io/dsover/bundle-categories:latest ]  container-tool=docker
INFO[0001] running docker cp                             container-tool=docker
DEBU[0001] [docker cp c34e972aa2841489317a82b403252bf48d9795f3c194cc76891c20bbd0aa68cc:/. /var/folders/9z/c4spd5wn0q51kw278nmpsjpm0000gn/T/bundle-913462645]  container-tool=docker
INFO[0001] running docker rm                             container-tool=docker
DEBU[0001] [docker rm c34e972aa2841489317a82b403252bf48d9795f3c194cc76891c20bbd0aa68cc]  container-tool=docker
INFO[0001] Unpacked image layers, validating bundle image format & contents  container-tool=docker
DEBU[0001] Found manifests directory                     container-tool=docker
DEBU[0001] Found metadata directory                      container-tool=docker
DEBU[0001] Getting mediaType info from manifests directory  container-tool=docker
INFO[0001] Found annotations file                        container-tool=docker
INFO[0001] Could not find optional dependencies file     container-tool=docker
DEBU[0001] Validating bundle contents                    container-tool=docker
DEBU[0001] Validating "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition" from file "etcdbackups.etcd.database.coreos.com.crd.yaml"  container-tool=docker
DEBU[0001] Validating "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition" from file "etcdclusters.etcd.database.coreos.com.crd.yaml"  container-tool=docker
DEBU[0001] Validating "operators.coreos.com/v1alpha1, Kind=ClusterServiceVersion" from file "etcdoperator.v0.9.4.clusterserviceversion.yaml"  container-tool=docker
DEBU[0001] Validating "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition" from file "etcdrestores.etcd.database.coreos.com.crd.yaml"  container-tool=docker
DEBU[0001] Performing operatorhub validation             container-tool=docker
INFO[0001] All validation tests have been completed successfully  container-tool=docker
```

/hold cancel

2020-11-11 18:29 UTC, ankitathomas reviewed
/lgtm

2020-11-11 18:30 UTC, ankitathomas commented
/test e2e-aws

2020-11-20 14:57 UTC, exdx commented
bumping api dep for category bugfix
/hold

2020-11-20 20:53 UTC, exdx commented
/hold cancel 
rebased off v0.3.22

2020-11-20 21:07 UTC, kevinrizza commented
/approve

2020-11-20 21:14 UTC, hasbro17 approved these changes
/lgtm

2020-11-21 00:15 UTC, exdx commented
/override codecov/patch
/override codecov/project

2020-11-21 00:18 UTC, merged