fix(opm-index-add) Throw error when a bundle is invalid
operator-framework/operator-registry pull request #522
Opened 2020-11-18 22:04 UTC by anik120

**Description of the change:**

With the introduction of #503, when a bundle from the list of bundles
being added with the `opm index add` command was invalid, opm was not
throwing an error, and was building the index with the valid bundles
instead, even when the `permissive` mode was not enabled. This PR
fixes the issue.

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

2020-11-18 22:08 UTC, dinhxuanvu reviewed
Looking good but just a quick comment.

2020-11-18 22:08 UTC, dinhxuanvu commented on pkg/registry/input_stream.go
> +			return image, utilerrors.NewAggregate(errs)
Should we add `packageErrs` into the `errs` before return?

2020-11-18 23:25 UTC, njhale requested changes

2020-11-18 23:25 UTC, njhale commented on pkg/registry/input_stream.go
> +			return image, utilerrors.NewAggregate(errs)
this fix looks incorrect
the way this should work is, as long as we find a bundle that works for at least one package, don't return an error 
eventually next will have no bundles, or bundles that cause errors on add

2020-11-19 02:31 UTC, njhale commented on pkg/registry/input_stream.go
> +			return image, utilerrors.NewAggregate(errs)
I've opened #523, which I believe fixes the regression. It also adds a test that fails before/succeeds after the change.

@anik120 PTAL, and let me know if you agree with the fix.

2020-11-19 15:58 UTC, anik120 commented
Closing in favor of #523

2020-11-19 15:58 UTC, closed without merging