Add doc on opm v1.15.3 index add behavior
operator-framework/operator-registry pull request #559
Opened 2021-01-19 18:40 UTC by bentito

**Description of the change:**

Add documentation for `opm v.15.3 index add` behavior.

**Motivation for the change:**

`opm v.15.3 index add` behavior has changed and needs documentation.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

2021-01-19 18:52 UTC, gallettilance approved these changes
/lgtm

2021-01-19 22:43 UTC, bentito commented
/retest

2021-01-20 13:46 UTC, bentito commented
/test e2e-aws

2021-01-20 15:26 UTC, bentito commented
/approve

2021-01-20 15:27 UTC, bentito commented
/assign @benluddy

2021-01-20 15:39 UTC, gallettilance commented
/bugzilla refresh

2021-01-20 15:52 UTC, bentito commented
/bugzilla refresh

2021-01-20 20:18 UTC, gallettilance commented
@bentito From Nick:
> If a given CSV is missing a version field, all CSVs (sourced from the command's arguments) belonging package are elided from the input. Additionally, a non-zero exit code is returned from the command.
CSVs without a version (and with duplicate versions) that are already part of the index are allowed so long as there is at least one CSV with a version field in the package that we can recognize as having the maximum version.
When --overwrite-latest is set, all bundle in a package are deleted and passed in as "input", and thus are constrained by the rules set out in the first paragraph above; the exceptions set out in the second paragraph above do not apply, and violations cause the offending package to be excluded from the index.

2021-01-20 20:40 UTC, bentito commented
> @bentito From Nick:
> 
> > If a given CSV is missing a version field, all CSVs (sourced from the command's arguments) belonging package are elided from the input. Additionally, a non-zero exit code is returned from the command.
> > CSVs without a version (and with duplicate versions) that are already part of the index are allowed so long as there is at least one CSV with a version field in the package that we can recognize as having the maximum version.
> > When --overwrite-latest is set, all bundle in a package are deleted and passed in as "input", and thus are constrained by the rules set out in the first paragraph above; the exceptions set out in the second paragraph above do not apply, and violations cause the offending package to be excluded from the index.

@njhale I think you're the Nick in question? If you wouldn't mind, could you make the comments as line comments to the file changes, it would help me understand what's being asked for, for changes.

2021-01-22 14:45 UTC, gallettilance requested changes

2021-01-22 14:45 UTC, gallettilance commented on docs/design/opm-tooling.md
> +CSVs without a version (and with duplicate versions) that are already part of the index are allowed so long as there is at least one CSV with a version field in the package that we can recognize as h
```suggestion
CSVs without a version (and with duplicate versions) that are already part of the index are allowed so long as there is at least one CSV with a version field in the package that we can recognize as having the maximum version. However, the presence of such CSVs will prevent the use of the `--overwrite-latest` flag.
```

2021-01-22 20:37 UTC, bentito commented
/test e2e-aws

2021-01-25 20:05 UTC, njhale requested changes
Some minor comments.

@benluddy and I discussed adding this content to the command help long-text at a later date.

2021-01-25 20:05 UTC, njhale commented on docs/design/opm-tooling.md
> +When `--overwrite-latest` is set, all bundle in a package are deleted and passed in as "input", and thus are constrained by the rules set out in the first paragraph above; the exceptions set out in t
```suggestion
When overwriting a bundle using the `--overwrite-latest` flag,  all existing bundles of the same package are removed before being re-added alongside the new bundle. As such, they are constrained by the rules set out in the first paragraph above; the exceptions set out in the second paragraph above do not apply, and violations cause the offending package to be excluded from the index.
```

2021-01-26 15:08 UTC, bentito commented on docs/design/opm-tooling.md
> +- `--overwrite-latest` causes all bundle in a package are deleted and passed in as "input".
agreed, removing

2021-01-28 16:50 UTC, bentito commented
/retest

2021-01-28 21:29 UTC, gallettilance commented
\lgtm

2021-02-08 19:00 UTC, merged