Use fedora as base for image builder
operator-framework/operator-registry pull request #683
Opened 2021-06-16 12:59 UTC by kevinrizza

Remove dependencies on Openshift and DockerHub for image build steps

2021-06-16 13:35 UTC, njhale requested changes

2021-06-16 13:35 UTC, njhale commented on upstream-builder.Dockerfile
> +FROM quay.io/fedora/fedora:34-x86_64 as builder
Was there a reason to change this from `alpine`? 

I suspect this image build is also broken now due to the `apk` calls below.

2021-06-16 13:35 UTC, njhale commented on upstream-builder.Dockerfile
> +FROM quay.io/fedora/fedora:34-x86_64 as builder
Can we rename this `Dockerfile` and drop the original?

2021-06-16 13:35 UTC, njhale commented on Dockerfile
There are still a lot of openshift specifics in this file. I'm wondering if we can drop it entirely.

2021-11-08 14:33 UTC, joelanford commented
@kevinrizza can this PR be closed out now that we're building via goreleaser and distroless?

2022-02-19 04:09 UTC, closed without merging