fix(opm): clarify that bundle declcfgs are not valid refs alone
operator-framework/operator-registry pull request #741
Opened 2021-08-05 01:11 UTC by estroz

**Description of the change:** clarify that bundle declcfgs are not valid refs alone, and require an `olm.package` declcfg.

**Motivation for the change:** diff is really intended for indices. There's no way to infer which channel is the default for a package if more than one bundle in the same package is passed to diff either, so we could get non-deterministic behavior unless diff imposes some ordering on channels. Assuming icon doesn't exist (or other future `olm.package` fields) for a package may cause issues when using the diff'ed catalog in-cluster too.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

2021-08-05 01:55 UTC, ankitathomas approved these changes
/lgtm

2021-08-05 01:57 UTC, joelanford commented on internal/action/diff.go
> +			if isNotAllowedError(err) {
Can you add unit tests to cover both old and new refs being bundles?

2021-08-06 14:37 UTC, joelanford commented
/lgtm

2021-08-10 13:26 UTC, awgreene requested changes
Nice work @estroz, a few nits.

2021-08-10 13:26 UTC, awgreene commented on internal/action/render.go
> +				return nil, fmt.Errorf("cannot render DC directory: %w", ErrNotAllowed)
Might be worth writing DeclarativeConfig out for users unfamiliar with the type.

2021-08-10 13:26 UTC, awgreene commented on internal/action/render.go
> +			return nil, fmt.Errorf("cannot render DC image: %w", ErrNotAllowed)
Same as above.

2021-08-10 16:34 UTC, estroz commented on cmd/opm/alpha/diff/cmd.go
> +a valid "olm.package" declarative config object referring to the bundle's package must exist in all input refs.
Done.

2021-08-11 19:26 UTC, dinhxuanvu approved these changes
/approve

2021-08-11 19:38 UTC, joelanford commented
/lgtm

2021-08-11 19:41 UTC, merged