feat(constraint): Add constraint type validation to bundle validation
operator-framework/operator-registry pull request #881
Opened 2021-12-13 19:00 UTC by dinhxuanvu

**Description of the change:**

A new type of dependency named constraint (olm.constraint) which uses
CEL expression is introduced in OLM. This new type is added to
dependencies.json file in the bundle just like gvk and package
dependencies. As a result, a new validation for constraint type
is added to ensure this type will be validated for bundle
dependencies.

Signed-off-by: Vu Dinh <vudinh@outlook.com>

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

2021-12-13 19:36 UTC, anik120 requested changes
Looks good, a few test cases should get it ready to go.

2021-12-14 16:48 UTC, estroz commented on pkg/registry/types.go
> +			errs = append(errs, fmt.Errorf("The CEL expression is missing"))
```suggestion
			errs = append(errs, fmt.Errorf("The CEL expression is missing"))
			continue
```

2021-12-14 16:49 UTC, estroz commented on pkg/registry/types.go
> +		dep := CelConstraint{}
Shouldn't this be decoded into an api `constraints.Constraint`?

2021-12-14 16:49 UTC, estroz commented
Agreed on unit tests.

2021-12-15 15:18 UTC, closed without merging